# Generated by Django 5.0.7 on 2024-07-10 19:13

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('bio', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('body', tinymce.models.HTMLField(blank=True, null=True)),
                ('inspirations', models.TextField(blank=True, null=True)),
                ('date_created', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visual_Poetry',
            fields=[
                ('writing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='writing.writing')),
                ('poem_css_file', models.FileField(null=True, upload_to='visual_poetry/poem_css')),
            ],
            bases=('writing.writing',),
        ),
        migrations.CreateModel(
            name='Writing_Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='writing.author')),
                ('writing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writings', to='writing.writing')),
            ],
        ),
    ]
