# Generated by Django 5.0.7 on 2024-10-31 03:02

import django.db.models.deletion
import django.db.models.manager
import markdownx.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('bio', markdownx.models.MarkdownxField(blank=True, null=True)),
                ('blurb', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Writing_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Writing_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Writing_Topic_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('body', markdownx.models.MarkdownxField(blank=True, null=True)),
                ('inspirations', models.TextField(blank=True, null=True)),
                ('date_created', models.DateField()),
                ('published', models.BooleanField(blank=True, default=False, null=True)),
                ('full_html_override', models.BooleanField(blank=True, default=False, null=True)),
                ('writing_css_file', models.FileField(null=True, upload_to='writing/css')),
                ('authors', models.ManyToManyField(to='writing.author')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writing.writing_category')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='writing.writing_project')),
                ('tag', models.ManyToManyField(null=True, to='writing.writing_topic_tag')),
            ],
            managers=[
                ('writings', django.db.models.manager.Manager()),
            ],
        ),
    ]
