# Generated by Django 5.0.7 on 2024-07-15 21:53

import django.db.models.deletion
import markdownx.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('bio', markdownx.models.MarkdownxField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('body', markdownx.models.MarkdownxField(blank=True, null=True)),
                ('inspirations', models.TextField(blank=True, null=True)),
                ('date_created', models.DateField()),
                ('published', models.BooleanField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('article_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writing.article_category')),
                ('authors', models.ManyToManyField(to='writing.author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Visual_Poetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('body', markdownx.models.MarkdownxField(blank=True, null=True)),
                ('inspirations', models.TextField(blank=True, null=True)),
                ('date_created', models.DateField()),
                ('published', models.BooleanField(blank=True, null=True)),
                ('poem_css_file', models.FileField(null=True, upload_to='visual_poetry/poem_css')),
                ('authors', models.ManyToManyField(to='writing.author')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
