# Generated by Django 5.0.7 on 2024-07-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writing',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
