# Generated by Django 5.0.7 on 2024-10-31 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writing',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='writing',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='writing.writing_project'),
        ),
        migrations.AlterField(
            model_name='writing',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='writing.writing_topic_tag'),
        ),
        migrations.AlterField(
            model_name='writing',
            name='writing_css_file',
            field=models.FileField(blank=True, null=True, upload_to='writing/css'),
        ),
    ]
