# Generated by Django 5.0.7 on 2024-07-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0002_alter_writing_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
