# Generated by Django 5.0.7 on 2024-11-02 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0002_remove_writing_user_id_alter_writing_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writing',
            old_name='tag',
            new_name='tags',
        ),
    ]
