# Generated by Django 5.0.7 on 2024-07-10 19:33

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0003_alter_author_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writing',
            name='body',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
