# Generated by Django 5.0.7 on 2024-07-10 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0005_alter_author_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('writing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='writing.writing')),
                ('article_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writing.article_category')),
            ],
            bases=('writing.writing',),
        ),
    ]
