# Generated by Django 5.0.7 on 2024-07-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0006_article_category_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='published',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
