# Generated by Django 5.0.7 on 2024-07-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0007_writing_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='authors',
            field=models.ManyToManyField(to='writing.author'),
        ),
        migrations.DeleteModel(
            name='Writing_Author',
        ),
    ]
