# Generated by Django 5.0.7 on 2024-07-10 19:13

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=400)),
                ('cover_image', models.ImageField(upload_to='albums')),
                ('release_date', models.DateField()),
                ('type', models.TextField(choices=[('EP', 'EP'), ('LP', 'LP'), ('S', 'Single'), ('A', 'Album'), ('C', 'Collection')])),
                ('description', models.TextField(blank=True, max_length=800, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            managers=[
                ('albums', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=400)),
                ('description', models.TextField(blank=True, max_length=800, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            managers=[
                ('songs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Album_Sales_Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(max_length=800)),
                ('url_display', models.TextField(blank=True, max_length=100, null=True)),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_links', to='portfolio_music_player.album')),
            ],
            managers=[
                ('album_sales_links', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Song_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='songs')),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_files', to='portfolio_music_player.song')),
            ],
        ),
        migrations.CreateModel(
            name='Track_Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_num', models.PositiveSmallIntegerField()),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='portfolio_music_player.album')),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_nums', to='portfolio_music_player.song')),
            ],
            options={
                'unique_together': {('song_id', 'album_id')},
            },
            managers=[
                ('track_numbers', django.db.models.manager.Manager()),
            ],
        ),
    ]
