# Generated by Django 4.0.4 on 2022-07-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_music_player', '0002_remove_song_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='description',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
    ]
