# Generated by Django 4.0.4 on 2022-05-20 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CV_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.TextField()),
                ('priority', models.PositiveSmallIntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('category_name', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='CV_Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('entry', models.TextField(max_length=300)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.cv_category')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField()),
                ('title', models.TextField(max_length=50)),
                ('image', models.ImageField(upload_to='projects')),
                ('short_description', models.TextField(max_length=120)),
                ('long_description', models.TextField(max_length=600)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Page_Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(choices=[('H', 'Home'), ('P', 'Projects'), ('R', 'Resume')])),
                ('image', models.ImageField(upload_to='page_headers')),
                ('title', models.TextField(max_length=25)),
                ('body', models.TextField(max_length=25)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='CV_Sub_Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_entry', models.TextField(max_length=300)),
                ('cv_line_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.cv_line')),
            ],
            options={
                'unique_together': {('cv_line_id', 'sub_entry')},
            },
        ),
    ]
