# Generated by Django 5.0.7 on 2024-07-10 19:13

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CV_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('priority', models.PositiveSmallIntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'user_id')},
            },
            managers=[
                ('cv_categories', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CV_Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('entry', models.TextField(max_length=300)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.cv_category')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('cv_lines', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField()),
                ('title', models.TextField(max_length=50)),
                ('image', models.ImageField(upload_to='projects')),
                ('image_alt_text', models.TextField(default='picture description', max_length=50)),
                ('short_description', models.TextField(max_length=120)),
                ('long_description', models.TextField(max_length=600)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('url', models.TextField(blank=True, max_length=100, null=True)),
                ('url_title', models.TextField(blank=True, max_length=20, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('projects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Page_Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(choices=[('Home', 'Home page'), ('Projects', 'Projects page'), ('Resume', 'Resume page')])),
                ('alignment', models.TextField(choices=[('L', 'Picture left aligned'), ('R', 'Picture right aligned'), ('C', 'Picture/text centered')], default='L')),
                ('image', models.ImageField(upload_to='page_headers')),
                ('image_alt_text', models.TextField(default='picture description', max_length=50)),
                ('title', models.TextField(max_length=25)),
                ('body', models.TextField(max_length=700)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'user_id')},
            },
            managers=[
                ('page_headers', django.db.models.manager.Manager()),
            ],
        ),
    ]
