# Generated by Django 4.0.4 on 2022-05-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_project_managers_alter_cv_line_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='url_title',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Project_Link',
        ),
    ]
