# Generated by Django 4.0.4 on 2022-05-25 17:35

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_project_url_project_url_title_delete_project_link'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cv_category',
            managers=[
                ('cv_categories', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='cv_line',
            managers=[
                ('cv_lines', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='cv_sub_line',
            managers=[
                ('cv_sub_lines', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='page_header',
            managers=[
                ('page_headers', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='page_header',
            name='body',
            field=models.TextField(max_length=700),
        ),
        migrations.AlterField(
            model_name='page_header',
            name='name',
            field=models.TextField(choices=[('Home', 'Home page'), ('Projects', 'Projects page'), ('Resume', 'Resume page')]),
        ),
    ]
