# Generated by Django 4.0.4 on 2022-05-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_cv_category_managers_alter_cv_line_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page_header',
            name='alignment',
            field=models.TextField(choices=[('L', 'Picture left aligned'), ('R', 'Picture right aligned'), ('C', 'Picture/text centered')], default='L'),
        ),
    ]
