# Generated by Django 4.0.4 on 2022-05-27 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_page_header_alignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv_sub_line',
            old_name='cv_line_id',
            new_name='cv_line',
        ),
    ]
