# Generated by Django 4.0.4 on 2022-05-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_rename_cv_line_id_cv_sub_line_cv_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='page_header',
            name='image_alt_text',
            field=models.TextField(default='picture description', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='image_alt_text',
            field=models.TextField(default='picture description', max_length=50),
        ),
    ]
