# Generated by Django 4.0.4 on 2022-05-27 22:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0008_page_header_image_alt_text_project_image_alt_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv_category',
            old_name='category_name',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='cv_category',
            unique_together={('name', 'user_id')},
        ),
    ]
