# Generated by Django 4.0.4 on 2022-05-27 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_rename_category_name_cv_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv_sub_line',
            old_name='sub_entry',
            new_name='entry',
        ),
        migrations.AlterUniqueTogether(
            name='cv_sub_line',
            unique_together={('cv_line', 'entry')},
        ),
    ]
